# version 1.0

#FROM ubuntu:14.04
FROM 9d60f519bcc5

MAINTAINER zhujun@cienet.com.cn

# Install tools
COPY tctools/ /opt/tctools
RUN cd /opt/tctools/ant;tar zxvf apache-ant-1.9.4-bin.tar.gz;rm apache-ant-1.9.4-bin.tar.gz
RUN cd /opt/tctools/jboss;tar zxvf wildfly-8.2.1.Final.tar.gz;rm wildfly-8.2.1.Final.tar.gz
RUN cd /opt/tctools/jdk;tar zxvf jdk-8u25-linux-x64.gz;rm jdk-8u25-linux-x64.gz

# Install tas
COPY tashome/ /root/tashome
RUN cd ~/tashome;tar zxvf tasprod-TAS-OFF-R6V4-jboss-20150907-0945.tar.gz;rm tasprod-TAS-OFF-R6V4-jboss-20150907-0945.tar.gz
RUN echo ". ~/tashome/tasrtenv.sh" >> ~/.bashrc
RUN echo "sudo service mysqld start" >> ~/.bashrc
RUN echo "tasstart.sh -ml" >> ~/.bashrc

ADD ./init.sh /opt/init.shd
RUN echo "if [ -f /opt/init.sh ]; then . /opt/init.sh ; rm /opt/init.sh ;fi" >> /etc/bash.bashrc

#RUN rm /bin/sh && ln -s /bin/bash /bin/sh
#RUN . ~/init.sh
#RUN /bin/bash -c "source ~/tashome/tasrtenv.sh"
#RUN /bin/bash -c "cd ~/tashome/prod/unix/script;sh taspatch.sh"
#RUN /bin/bash -c "./~/tashome/prod/unix/script/tasdbinit.sh"

EXPOSE 6500
